### ISSUE TITLE
Connect the machine and optionally act as a subnet router

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-tailscale#1]
## Proposed feature

Installing Tailscale, OK. How about joining the VPN? How about acting as a subnet router?

## Rationale

This version is a good start, but it lacks some features.

## Additional context

Compare for instance the tailscale role I made, and feel free to steal from it:

https://github.com/dockpack/base_tailscale/blob/main/tasks/linux.yml

**Comment by robertdebock** [comment]
Hey @bbaassssiiee, I agree. I've added authentication and exit-node options.

Better?

**Comment by bbaassssiiee** [comment]
Yes, but I notice the use of `yes/no` for Booleans, I think `true/false` is cleaner.

**Comment by robertdebock** [comment]
About the booleans; That's a preference. Ansible Lint [suggests to use `true` or `false`](https://yamllint.readthedocs.io/en/stable/rules.html#id23), but I don't agree. In my opinion `yes` and `no` are more natural to read.

Thanks for the input anyway Bas.

I've added the "advertise routes" feature.

**Comment by bbaassssiiee** [comment]
YAML 1.2 only has `true` and `false`, so better prepare for yet another parser. In yaml 1.1 `yes` and `no` are only valid for yaml input, `true` and `false` are valid yaml and json, these are returned from the modules. So `yes` turns into `true`, and `no` turns into `false`. If you use the return values you'll appreciate the consistency that yamllint suggests.
